import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./RegistrationMap.scss";
import { SubmitHandler, useForm } from "react-hook-form";
import CssBaseline from "@mui/material/CssBaseline";
import fetchMap from "../../../api/mapFetch";
import $ from "jquery";

function mapSelector() {
  let coordinateX = 0;
  let coordinateY = 0;
  const navigate = useNavigate();

  function randomCoordinates() {
    coordinateX = Math.ceil(Math.random() * 100);
    coordinateY = Math.ceil(Math.random() * 100);
    navigate("/");
    // write to database;
  }

  function confirm() {
    navigate("/");
  }

  function selected() {
    console.log("click");
  }

  $(document.body).click(function (evt) {
    const clicked = evt.target;
    const currentID = clicked.id || "No ID!";
    // $(clicked).html(currentID);
    console.log(currentID)
    $('#theDiv').prepend('<img id="theImg" src="../../../../../docs/Strigops new pictures/Spaceship/spaceships.png" />')
  });

  return (
    <div className="RegistrationMap">
      <h1 className="imperiumName">Choose a place in space to colonize it!</h1>{" "}
      {/* to be fetched from backend */}
      <div className="MapGridContainer" onClick={selected}>
        <div className="map" id="1"></div>
        <div className="map" id="2"></div>
        <div className="map" id="3"></div>
        <div className="map" id="4"></div>
        <div className="map" id="5"></div>
        <div className="map" id="6"></div>
        <div className="map" id="7"></div>
        <div className="map" id="8"></div>
        <div className="map" id="9"></div>
        <div className="map" id="10"></div>
        <div className="map" id="11"></div>
        <div className="map" id="12"></div>
        <div className="map" id="13"></div>
        <div className="map" id="14"></div>
        <div className="map" id="15"></div>
        <div className="map" id="16"></div>
        <div className="map" id="17"></div>
        <div className="map" id="18"></div>
        <div className="map" id="19"></div>
        <div className="map" id="20"></div>
        <div className="map" id="21"></div>
        <div className="map" id="22"></div>
        <div className="map" id="23"></div>
        <div className="map" id="24"></div>
        <div className="map" id="25"></div>
        <div className="map" id="26"></div>
        <div className="map" id="27"></div>
        <div className="map" id="28"></div>
        <div className="map" id="29"></div>
        <div className="map" id="30"></div>
        <div className="map" id="31"></div>
        <div className="map" id="32"></div>
        <div className="map" id="33"></div>
        <div className="map" id="34"></div>
        <div className="map" id="35"></div>
        <div className="map" id="36"></div>
        <div className="map" id="37"></div>
        <div className="map" id="38"></div>
        <div className="map" id="39"></div>
        <div className="map" id="40"></div>
        <div className="map" id="41"></div>
        <div className="map" id="42"></div>
        <div className="map" id="43"></div>
        <div className="map" id="44"></div>
        <div className="map" id="45"></div>
        <div className="map" id="46"></div>
        <div className="map" id="47"></div>
        <div className="map" id="48"></div>
        <div className="map" id="49"></div>
        <div className="map" id="50"></div>
        <div className="map" id="51"></div>
        <div className="map" id="52"></div>
        <div className="map" id="53"></div>
        <div className="map" id="54"></div>
        <div className="map" id="55"></div>
        <div className="map" id="56"></div>
        <div className="map" id="57"></div>
        <div className="map" id="58"></div>
        <div className="map" id="59"></div>
        <div className="map" id="60"></div>
        <div className="map" id="61"></div>
        <div className="map" id="62"></div>
        <div className="map" id="63"></div>
        <div className="map" id="64"></div>
        <div className="map" id="65"></div>
        <div className="map" id="66"></div>
        <div className="map" id="67"></div>
        <div className="map" id="68"></div>
        <div className="map" id="69"></div>
        <div className="map" id="70"></div>
        <div className="map" id="71"></div>
        <div className="map" id="72"></div>
        <div className="map" id="73"></div>
        <div className="map" id="74"></div>
        <div className="map" id="75"></div>
        <div className="map" id="76"></div>
        <div className="map" id="77"></div>
        <div className="map" id="78"></div>
        <div className="map" id="79"></div>
        <div className="map" id="80"></div>
        <div className="map" id="81"></div>
        <div className="map" id="82"></div>
        <div className="map" id="83"></div>
        <div className="map" id="84"></div>
        <div className="map" id="85"></div>
        <div className="map" id="86"></div>
        <div className="map" id="87"></div>
        <div className="map" id="88"></div>
        <div className="map" id="89"></div>
        <div className="map" id="90"></div>
        <div className="map" id="91"></div>
        <div className="map" id="92"></div>
        <div className="map" id="93"></div>
        <div className="map" id="94"></div>
        <div className="map" id="95"></div>
        <div className="map" id="96"></div>
        <div className="map" id="97"></div>
        <div className="map" id="98"></div>
        <div className="map" id="99"></div>
        <div className="map" id="100"></div>
        <div className="map" id="101"></div>
        <div className="map" id="102"></div>
        <div className="map" id="103"></div>
        <div className="map" id="104"></div>
        <div className="map" id="105"></div>
        <div className="map" id="106"></div>
        <div className="map" id="107"></div>
        <div className="map" id="108"></div>
        <div className="map" id="109"></div>
        <div className="map" id="110"></div>
        <div className="map" id="111"></div>
        <div className="map" id="112"></div>
        <div className="map" id="113"></div>
        <div className="map" id="114"></div>
        <div className="map" id="115"></div>
        <div className="map" id="116"></div>
        <div className="map" id="117"></div>
        <div className="map" id="118"></div>
        <div className="map" id="119"></div>
        <div className="map" id="120"></div>
        <div className="map" id="121"></div>
        <div className="map" id="122"></div>
        <div className="map" id="123"></div>
        <div className="map" id="124"></div>
        <div className="map" id="125"></div>
        <div className="map" id="126"></div>
        <div className="map" id="127"></div>
        <div className="map" id="128"></div>
        <div className="map" id="129"></div>
        <div className="map" id="130"></div>
        <div className="map" id="131"></div>
        <div className="map" id="132"></div>
        <div className="map" id="133"></div>
        <div className="map" id="134"></div>
        <div className="map" id="135"></div>
        <div className="map" id="136"></div>
        <div className="map" id="137"></div>
        <div className="map" id="138"></div>
        <div className="map" id="139"></div>
        <div className="map" id="140"></div>
        <div className="map" id="141"></div>
        <div className="map" id="142"></div>
        <div className="map" id="143"></div>
        <div className="map" id="144"></div>
        <div className="map" id="145"></div>
        <div className="map" id="146"></div>
        <div className="map" id="147"></div>
        <div className="map" id="148"></div>
        <div className="map" id="149"></div>
        <div className="map" id="150"></div>
        <div className="map" id="151"></div>
        <div className="map" id="152"></div>
        <div className="map" id="153"></div>
        <div className="map" id="154"></div>
        <div className="map" id="155"></div>
        <div className="map" id="156"></div>
        <div className="map" id="157"></div>
        <div className="map" id="158"></div>
        <div className="map" id="159"></div>
        <div className="map" id="160"></div>
        <div className="map" id="161"></div>
        <div className="map" id="162"></div>
        <div className="map" id="163"></div>
        <div className="map" id="164"></div>
        <div className="map" id="165"></div>
        <div className="map" id="166"></div>
        <div className="map" id="167"></div>
        <div className="map" id="168"></div>
        <div className="map" id="169"></div>
        <div className="map" id="170"></div>
        <div className="map" id="171"></div>
        <div className="map" id="172"></div>
        <div className="map" id="173"></div>
        <div className="map" id="174"></div>
        <div className="map" id="175"></div>
        <div className="map" id="176"></div>
        <div className="map" id="177"></div>
        <div className="map" id="178"></div>
        <div className="map" id="179"></div>
        <div className="map" id="180"></div>
        <div className="map" id="181"></div>
        <div className="map" id="182"></div>
        <div className="map" id="183"></div>
        <div className="map" id="184"></div>
        <div className="map" id="185"></div>
        <div className="map" id="186"></div>
        <div className="map" id="187"></div>
        <div className="map" id="188"></div>
        <div className="map" id="189"></div>
        <div className="map" id="190"></div>
        <div className="map" id="191"></div>
        <div className="map" id="192"></div>
        <div className="map" id="193"></div>
        <div className="map" id="194"></div>
        <div className="map" id="195"></div>
        <div className="map" id="196"></div>
        <div className="map" id="197"></div>
        <div className="map" id="198"></div>
        <div className="map" id="199"></div>
        <div className="map" id="200"></div>
        <div className="map" id="201"></div>
        <div className="map" id="202"></div>
        <div className="map" id="203"></div>
        <div className="map" id="204"></div>
        <div className="map" id="205"></div>
        <div className="map" id="206"></div>
        <div className="map" id="207"></div>
        <div className="map" id="208"></div>
        <div className="map" id="209"></div>
        <div className="map" id="210"></div>
        <div className="map" id="211"></div>
        <div className="map" id="212"></div>
        <div className="map" id="213"></div>
        <div className="map" id="214"></div>
        <div className="map" id="215"></div>
        <div className="map" id="216"></div>
        <div className="map" id="217"></div>
        <div className="map" id="218"></div>
        <div className="map" id="219"></div>
        <div className="map" id="220"></div>
        <div className="map" id="221"></div>
        <div className="map" id="222"></div>
        <div className="map" id="223"></div>
        <div className="map" id="224"></div>
        <div className="map" id="225"></div>
        <div className="map" id="226"></div>
        <div className="map" id="227"></div>
        <div className="map" id="228"></div>
        <div className="map" id="229"></div>
        <div className="map" id="230"></div>
        <div className="map" id="231"></div>
        <div className="map" id="232"></div>
        <div className="map" id="233"></div>
        <div className="map" id="234"></div>
        <div className="map" id="235"></div>
        <div className="map" id="236"></div>
        <div className="map" id="237"></div>
        <div className="map" id="238"></div>
        <div className="map" id="239"></div>
        <div className="map" id="240"></div>
        <div className="map" id="241"></div>
        <div className="map" id="242"></div>
        <div className="map" id="243"></div>
        <div className="map" id="244"></div>
        <div className="map" id="245"></div>
        <div className="map" id="246"></div>
        <div className="map" id="247"></div>
        <div className="map" id="248"></div>
        <div className="map" id="249"></div>
        <div className="map" id="250"></div>
        <div className="map" id="251"></div>
        <div className="map" id="252"></div>
        <div className="map" id="253"></div>
        <div className="map" id="254"></div>
        <div className="map" id="255"></div>
        <div className="map" id="256"></div>
        <div className="map" id="257"></div>
        <div className="map" id="258"></div>
        <div className="map" id="259"></div>
        <div className="map" id="260"></div>
        <div className="map" id="261"></div>
        <div className="map" id="262"></div>
        <div className="map" id="263"></div>
        <div className="map" id="264"></div>
        <div className="map" id="265"></div>
        <div className="map" id="266"></div>
        <div className="map" id="267"></div>
        <div className="map" id="268"></div>
        <div className="map" id="269"></div>
        <div className="map" id="270"></div>
        <div className="map" id="271"></div>
        <div className="map" id="272"></div>
        <div className="map" id="273"></div>
        <div className="map" id="274"></div>
        <div className="map" id="275"></div>
        <div className="map" id="276"></div>
        <div className="map" id="277"></div>
        <div className="map" id="278"></div>
        <div className="map" id="279"></div>
        <div className="map" id="280"></div>
        <div className="map" id="281"></div>
        <div className="map" id="282"></div>
        <div className="map" id="283"></div>
        <div className="map" id="284"></div>
        <div className="map" id="285"></div>
        <div className="map" id="286"></div>
        <div className="map" id="287"></div>
        <div className="map" id="288"></div>
        <div className="map" id="289"></div>
        <div className="map" id="290"></div>
        <div className="map" id="291"></div>
        <div className="map" id="292"></div>
        <div className="map" id="293"></div>
        <div className="map" id="294"></div>
        <div className="map" id="295"></div>
        <div className="map" id="296"></div>
        <div className="map" id="297"></div>
        <div className="map" id="298"></div>
        <div className="map" id="299"></div>
        <div className="map" id="300"></div>
        <div className="map" id="301"></div>
        <div className="map" id="302"></div>
        <div className="map" id="303"></div>
        <div className="map" id="304"></div>
        <div className="map" id="305"></div>
        <div className="map" id="306"></div>
        <div className="map" id="307"></div>
        <div className="map" id="308"></div>
        <div className="map" id="309"></div>
        <div className="map" id="310"></div>
        <div className="map" id="311"></div>
        <div className="map" id="312"></div>
        <div className="map" id="313"></div>
        <div className="map" id="314"></div>
        <div className="map" id="315"></div>
        <div className="map" id="316"></div>
        <div className="map" id="317"></div>
        <div className="map" id="318"></div>
        <div className="map" id="319"></div>
        <div className="map" id="320"></div>
        <div className="map" id="321"></div>
        <div className="map" id="322"></div>
        <div className="map" id="323"></div>
        <div className="map" id="324"></div>
        <div className="map" id="325"></div>
        <div className="map" id="326"></div>
        <div className="map" id="327"></div>
        <div className="map" id="328"></div>
        <div className="map" id="329"></div>
        <div className="map" id="330"></div>
        <div className="map" id="331"></div>
        <div className="map" id="332"></div>
        <div className="map" id="333"></div>
        <div className="map" id="334"></div>
        <div className="map" id="335"></div>
        <div className="map" id="336"></div>
        <div className="map" id="337"></div>
        <div className="map" id="338"></div>
        <div className="map" id="339"></div>
        <div className="map" id="340"></div>
        <div className="map" id="341"></div>
        <div className="map" id="342"></div>
        <div className="map" id="343"></div>
        <div className="map" id="344"></div>
        <div className="map" id="345"></div>
        <div className="map" id="346"></div>
        <div className="map" id="347"></div>
        <div className="map" id="348"></div>
        <div className="map" id="349"></div>
        <div className="map" id="350"></div>
        <div className="map" id="351"></div>
        <div className="map" id="352"></div>
        <div className="map" id="353"></div>
        <div className="map" id="354"></div>
        <div className="map" id="355"></div>
        <div className="map" id="356"></div>
        <div className="map" id="357"></div>
        <div className="map" id="358"></div>
        <div className="map" id="359"></div>
        <div className="map" id="360"></div>
        <div className="map" id="361"></div>
        <div className="map" id="362"></div>
        <div className="map" id="363"></div>
        <div className="map" id="364"></div>
        <div className="map" id="365"></div>
        <div className="map" id="366"></div>
        <div className="map" id="367"></div>
        <div className="map" id="368"></div>
        <div className="map" id="369"></div>
        <div className="map" id="370"></div>
        <div className="map" id="371"></div>
        <div className="map" id="372"></div>
        <div className="map" id="373"></div>
        <div className="map" id="374"></div>
        <div className="map" id="375"></div>
        <div className="map" id="376"></div>
        <div className="map" id="377"></div>
        <div className="map" id="378"></div>
        <div className="map" id="379"></div>
        <div className="map" id="380"></div>
        <div className="map" id="381"></div>
        <div className="map" id="382"></div>
        <div className="map" id="383"></div>
        <div className="map" id="384"></div>
        <div className="map" id="385"></div>
        <div className="map" id="386"></div>
        <div className="map" id="387"></div>
        <div className="map" id="388"></div>
        <div className="map" id="389"></div>
        <div className="map" id="390"></div>
        <div className="map" id="391"></div>
        <div className="map" id="392"></div>
        <div className="map" id="393"></div>
        <div className="map" id="394"></div>
        <div className="map" id="395"></div>
        <div className="map" id="396"></div>
        <div className="map" id="397"></div>
        <div className="map" id="398"></div>
        <div className="map" id="399"></div>
        <div className="map" id="400"></div>
        <div className="map" id="401"></div>
        <div className="map" id="402"></div>
        <div className="map" id="403"></div>
        <div className="map" id="404"></div>
        <div className="map" id="405"></div>
        <div className="map" id="406"></div>
        <div className="map" id="407"></div>
        <div className="map" id="408"></div>
        <div className="map" id="409"></div>
        <div className="map" id="410"></div>
        <div className="map" id="411"></div>
        <div className="map" id="412"></div>
        <div className="map" id="413"></div>
        <div className="map" id="414"></div>
        <div className="map" id="415"></div>
        <div className="map" id="416"></div>
        <div className="map" id="417"></div>
        <div className="map" id="418"></div>
        <div className="map" id="419"></div>
        <div className="map" id="420"></div>
        <div className="map" id="421"></div>
        <div className="map" id="422"></div>
        <div className="map" id="423"></div>
        <div className="map" id="424"></div>
        <div className="map" id="425"></div>
        <div className="map" id="426"></div>
        <div className="map" id="427"></div>
        <div className="map" id="428"></div>
        <div className="map" id="429"></div>
        <div className="map" id="430"></div>
        <div className="map" id="431"></div>
        <div className="map" id="432"></div>
        <div className="map" id="433"></div>
        <div className="map" id="434"></div>
        <div className="map" id="435"></div>
        <div className="map" id="436"></div>
        <div className="map" id="437"></div>
        <div className="map" id="438"></div>
        <div className="map" id="439"></div>
        <div className="map" id="440"></div>
        <div className="map" id="441"></div>
        <div className="map" id="442"></div>
        <div className="map" id="443"></div>
        <div className="map" id="444"></div>
        <div className="map" id="445"></div>
        <div className="map" id="446"></div>
        <div className="map" id="447"></div>
        <div className="map" id="448"></div>
        <div className="map" id="449"></div>
        <div className="map" id="450"></div>
        <div className="map" id="451"></div>
        <div className="map" id="452"></div>
        <div className="map" id="453"></div>
        <div className="map" id="454"></div>
        <div className="map" id="455"></div>
        <div className="map" id="456"></div>
        <div className="map" id="457"></div>
        <div className="map" id="458"></div>
        <div className="map" id="459"></div>
        <div className="map" id="460"></div>
        <div className="map" id="461"></div>
        <div className="map" id="462"></div>
        <div className="map" id="463"></div>
        <div className="map" id="464"></div>
        <div className="map" id="465"></div>
        <div className="map" id="466"></div>
        <div className="map" id="467"></div>
        <div className="map" id="468"></div>
        <div className="map" id="469"></div>
        <div className="map" id="470"></div>
        <div className="map" id="471"></div>
        <div className="map" id="472"></div>
        <div className="map" id="473"></div>
        <div className="map" id="474"></div>
        <div className="map" id="475"></div>
        <div className="map" id="476"></div>
        <div className="map" id="477"></div>
        <div className="map" id="478"></div>
        <div className="map" id="479"></div>
        <div className="map" id="480"></div>
        <div className="map" id="481"></div>
        <div className="map" id="482"></div>
        <div className="map" id="483"></div>
        <div className="map" id="484"></div>
        <div className="map" id="485"></div>
        <div className="map" id="486"></div>
        <div className="map" id="487"></div>
        <div className="map" id="488"></div>
        <div className="map" id="489"></div>
        <div className="map" id="490"></div>
        <div className="map" id="491"></div>
        <div className="map" id="492"></div>
        <div className="map" id="493"></div>
        <div className="map" id="494"></div>
        <div className="map" id="495"></div>
        <div className="map" id="496"></div>
        <div className="map" id="497"></div>
        <div className="map" id="498"></div>
        <div className="map" id="499"></div>
        <div className="map" id="500"></div>
        <div className="map" id="501"></div>
        <div className="map" id="502"></div>
        <div className="map" id="503"></div>
        <div className="map" id="504"></div>
        <div className="map" id="505"></div>
        <div className="map" id="506"></div>
        <div className="map" id="507"></div>
        <div className="map" id="508"></div>
        <div className="map" id="509"></div>
        <div className="map" id="510"></div>
        <div className="map" id="511"></div>
        <div className="map" id="512"></div>
        <div className="map" id="513"></div>
        <div className="map" id="514"></div>
        <div className="map" id="515"></div>
        <div className="map" id="516"></div>
        <div className="map" id="517"></div>
        <div className="map" id="518"></div>
        <div className="map" id="519"></div>
        <div className="map" id="520"></div>
        <div className="map" id="521"></div>
        <div className="map" id="522"></div>
        <div className="map" id="523"></div>
        <div className="map" id="524"></div>
        <div className="map" id="525"></div>
        <div className="map" id="526"></div>
        <div className="map" id="527"></div>
        <div className="map" id="528"></div>
        <div className="map" id="529"></div>
        <div className="map" id="530"></div>
        <div className="map" id="531"></div>
        <div className="map" id="532"></div>
        <div className="map" id="533"></div>
        <div className="map" id="534"></div>
        <div className="map" id="535"></div>
        <div className="map" id="536"></div>
        <div className="map" id="537"></div>
        <div className="map" id="538"></div>
        <div className="map" id="539"></div>
        <div className="map" id="540"></div>
        <div className="map" id="541"></div>
        <div className="map" id="542"></div>
        <div className="map" id="543"></div>
        <div className="map" id="544"></div>
        <div className="map" id="545"></div>
        <div className="map" id="546"></div>
        <div className="map" id="547"></div>
        <div className="map" id="548"></div>
        <div className="map" id="549"></div>
        <div className="map" id="550"></div>
        <div className="map" id="551"></div>
        <div className="map" id="552"></div>
        <div className="map" id="553"></div>
        <div className="map" id="554"></div>
        <div className="map" id="555"></div>
        <div className="map" id="556"></div>
        <div className="map" id="557"></div>
        <div className="map" id="558"></div>
        <div className="map" id="559"></div>
        <div className="map" id="560"></div>
        <div className="map" id="561"></div>
        <div className="map" id="562"></div>
        <div className="map" id="563"></div>
        <div className="map" id="564"></div>
        <div className="map" id="565"></div>
        <div className="map" id="566"></div>
        <div className="map" id="567"></div>
        <div className="map" id="568"></div>
        <div className="map" id="569"></div>
        <div className="map" id="570"></div>
        <div className="map" id="571"></div>
        <div className="map" id="572"></div>
        <div className="map" id="573"></div>
        <div className="map" id="574"></div>
        <div className="map" id="575"></div>
        <div className="map" id="576"></div>
        <div className="map" id="577"></div>
        <div className="map" id="578"></div>
        <div className="map" id="579"></div>
        <div className="map" id="580"></div>
        <div className="map" id="581"></div>
        <div className="map" id="582"></div>
        <div className="map" id="583"></div>
        <div className="map" id="584"></div>
        <div className="map" id="585"></div>
        <div className="map" id="586"></div>
        <div className="map" id="587"></div>
        <div className="map" id="588"></div>
        <div className="map" id="589"></div>
        <div className="map" id="590"></div>
        <div className="map" id="591"></div>
        <div className="map" id="592"></div>
        <div className="map" id="593"></div>
        <div className="map" id="594"></div>
        <div className="map" id="595"></div>
        <div className="map" id="596"></div>
        <div className="map" id="597"></div>
        <div className="map" id="598"></div>
        <div className="map" id="599"></div>
        <div className="map" id="600"></div>
      </div>
      <div className="buttons">
        <button className="button" onClick={randomCoordinates}>
          RANDOM
        </button>
        <button className="button" onClick={confirm}>
          CONFIRM{" "}
        </button>
      </div>
    </div>
  );
}

export default mapSelector;
